/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/Sidebar/AppSidebar.vue')['default']
    CollapseSidebar: typeof import('./src/components/Icons/CollapseSidebar.vue')['default']
    DesktopLayout: typeof import('./src/components/DesktopLayout.vue')['default']
    InstallPrompt: typeof import('./src/components/InstallPrompt.vue')['default']
    MobileLayout: typeof import('./src/components/MobileLayout.vue')['default']
    NoSidebarLayout: typeof import('./src/components/NoSidebarLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/Sidebar/SidebarLink.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserDropdown: typeof import('./src/components/Sidebar/UserDropdown.vue')['default']
  }
}
